- name: Directory created
  file:
    path: /data/jenkins
    mode: 0777
    recurse: yes
    state: directory
  tags: [jenkins-master]

- name: Jenkins container is running
  docker_container:
    name: jenkins
    image: jenkins
    restart_policy: always
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
      - /usr/local/bin/whaleprint:/usr/local/bin/whaleprint
  tags: [jenkins-master]
